# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: image_classifier.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'image_classifier.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16image_classifier.proto\x12\x18org.example.modelbackend\"\"\n\x0cImageRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"c\n\rImageResponse\x12\r\n\x05label\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x17\n\x0fpreprocess_data\x18\x03 \x01(\x0c\x12\x16\n\x0e\x61ttention_data\x18\x04 \x01(\x0c\x32s\n\x0fImageClassifier\x12`\n\rClassifyImage\x12&.org.example.modelbackend.ImageRequest\x1a\'.org.example.modelbackend.ImageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_classifier_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=52
  _globals['_IMAGEREQUEST']._serialized_end=86
  _globals['_IMAGERESPONSE']._serialized_start=88
  _globals['_IMAGERESPONSE']._serialized_end=187
  _globals['_IMAGECLASSIFIER']._serialized_start=189
  _globals['_IMAGECLASSIFIER']._serialized_end=304
# @@protoc_insertion_point(module_scope)
