// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: image_classifier.proto
// Protobuf Java Version: 4.29.3

package org.example.modelbackend;

public final class ImageClassifierOuterClass {
  private ImageClassifierOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      ImageClassifierOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ImageRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.example.modelbackend.ImageRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes image_data = 1;</code>
     * @return The imageData.
     */
    com.google.protobuf.ByteString getImageData();
  }
  /**
   * Protobuf type {@code org.example.modelbackend.ImageRequest}
   */
  public static final class ImageRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.example.modelbackend.ImageRequest)
      ImageRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        ImageRequest.class.getName());
    }
    // Use ImageRequest.newBuilder() to construct.
    private ImageRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ImageRequest() {
      imageData_ = com.google.protobuf.ByteString.EMPTY;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.modelbackend.ImageClassifierOuterClass.internal_static_org_example_modelbackend_ImageRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.modelbackend.ImageClassifierOuterClass.internal_static_org_example_modelbackend_ImageRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.modelbackend.ImageClassifierOuterClass.ImageRequest.class, org.example.modelbackend.ImageClassifierOuterClass.ImageRequest.Builder.class);
    }

    public static final int IMAGE_DATA_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString imageData_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes image_data = 1;</code>
     * @return The imageData.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getImageData() {
      return imageData_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!imageData_.isEmpty()) {
        output.writeBytes(1, imageData_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!imageData_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, imageData_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.example.modelbackend.ImageClassifierOuterClass.ImageRequest)) {
        return super.equals(obj);
      }
      org.example.modelbackend.ImageClassifierOuterClass.ImageRequest other = (org.example.modelbackend.ImageClassifierOuterClass.ImageRequest) obj;

      if (!getImageData()
          .equals(other.getImageData())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IMAGE_DATA_FIELD_NUMBER;
      hash = (53 * hash) + getImageData().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.example.modelbackend.ImageClassifierOuterClass.ImageRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.modelbackend.ImageClassifierOuterClass.ImageRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.modelbackend.ImageClassifierOuterClass.ImageRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.modelbackend.ImageClassifierOuterClass.ImageRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.modelbackend.ImageClassifierOuterClass.ImageRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.modelbackend.ImageClassifierOuterClass.ImageRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.modelbackend.ImageClassifierOuterClass.ImageRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.example.modelbackend.ImageClassifierOuterClass.ImageRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.example.modelbackend.ImageClassifierOuterClass.ImageRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.example.modelbackend.ImageClassifierOuterClass.ImageRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.modelbackend.ImageClassifierOuterClass.ImageRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.example.modelbackend.ImageClassifierOuterClass.ImageRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.example.modelbackend.ImageClassifierOuterClass.ImageRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.example.modelbackend.ImageRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.example.modelbackend.ImageRequest)
        org.example.modelbackend.ImageClassifierOuterClass.ImageRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.example.modelbackend.ImageClassifierOuterClass.internal_static_org_example_modelbackend_ImageRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.example.modelbackend.ImageClassifierOuterClass.internal_static_org_example_modelbackend_ImageRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.example.modelbackend.ImageClassifierOuterClass.ImageRequest.class, org.example.modelbackend.ImageClassifierOuterClass.ImageRequest.Builder.class);
      }

      // Construct using org.example.modelbackend.ImageClassifierOuterClass.ImageRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        imageData_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.example.modelbackend.ImageClassifierOuterClass.internal_static_org_example_modelbackend_ImageRequest_descriptor;
      }

      @java.lang.Override
      public org.example.modelbackend.ImageClassifierOuterClass.ImageRequest getDefaultInstanceForType() {
        return org.example.modelbackend.ImageClassifierOuterClass.ImageRequest.getDefaultInstance();
      }

      @java.lang.Override
      public org.example.modelbackend.ImageClassifierOuterClass.ImageRequest build() {
        org.example.modelbackend.ImageClassifierOuterClass.ImageRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.example.modelbackend.ImageClassifierOuterClass.ImageRequest buildPartial() {
        org.example.modelbackend.ImageClassifierOuterClass.ImageRequest result = new org.example.modelbackend.ImageClassifierOuterClass.ImageRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.example.modelbackend.ImageClassifierOuterClass.ImageRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.imageData_ = imageData_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.example.modelbackend.ImageClassifierOuterClass.ImageRequest) {
          return mergeFrom((org.example.modelbackend.ImageClassifierOuterClass.ImageRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.example.modelbackend.ImageClassifierOuterClass.ImageRequest other) {
        if (other == org.example.modelbackend.ImageClassifierOuterClass.ImageRequest.getDefaultInstance()) return this;
        if (other.getImageData() != com.google.protobuf.ByteString.EMPTY) {
          setImageData(other.getImageData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                imageData_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString imageData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes image_data = 1;</code>
       * @return The imageData.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getImageData() {
        return imageData_;
      }
      /**
       * <code>bytes image_data = 1;</code>
       * @param value The imageData to set.
       * @return This builder for chaining.
       */
      public Builder setImageData(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        imageData_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>bytes image_data = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearImageData() {
        bitField0_ = (bitField0_ & ~0x00000001);
        imageData_ = getDefaultInstance().getImageData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.example.modelbackend.ImageRequest)
    }

    // @@protoc_insertion_point(class_scope:org.example.modelbackend.ImageRequest)
    private static final org.example.modelbackend.ImageClassifierOuterClass.ImageRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.example.modelbackend.ImageClassifierOuterClass.ImageRequest();
    }

    public static org.example.modelbackend.ImageClassifierOuterClass.ImageRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ImageRequest>
        PARSER = new com.google.protobuf.AbstractParser<ImageRequest>() {
      @java.lang.Override
      public ImageRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ImageRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ImageRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.example.modelbackend.ImageClassifierOuterClass.ImageRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ImageResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.example.modelbackend.ImageResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string label = 1;</code>
     * @return The label.
     */
    java.lang.String getLabel();
    /**
     * <code>string label = 1;</code>
     * @return The bytes for label.
     */
    com.google.protobuf.ByteString
        getLabelBytes();

    /**
     * <code>float confidence = 2;</code>
     * @return The confidence.
     */
    float getConfidence();

    /**
     * <code>bytes preprocess_data = 3;</code>
     * @return The preprocessData.
     */
    com.google.protobuf.ByteString getPreprocessData();

    /**
     * <code>bytes attention_data = 4;</code>
     * @return The attentionData.
     */
    com.google.protobuf.ByteString getAttentionData();
  }
  /**
   * Protobuf type {@code org.example.modelbackend.ImageResponse}
   */
  public static final class ImageResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.example.modelbackend.ImageResponse)
      ImageResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        ImageResponse.class.getName());
    }
    // Use ImageResponse.newBuilder() to construct.
    private ImageResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ImageResponse() {
      label_ = "";
      preprocessData_ = com.google.protobuf.ByteString.EMPTY;
      attentionData_ = com.google.protobuf.ByteString.EMPTY;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.modelbackend.ImageClassifierOuterClass.internal_static_org_example_modelbackend_ImageResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.modelbackend.ImageClassifierOuterClass.internal_static_org_example_modelbackend_ImageResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.modelbackend.ImageClassifierOuterClass.ImageResponse.class, org.example.modelbackend.ImageClassifierOuterClass.ImageResponse.Builder.class);
    }

    public static final int LABEL_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object label_ = "";
    /**
     * <code>string label = 1;</code>
     * @return The label.
     */
    @java.lang.Override
    public java.lang.String getLabel() {
      java.lang.Object ref = label_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        label_ = s;
        return s;
      }
    }
    /**
     * <code>string label = 1;</code>
     * @return The bytes for label.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLabelBytes() {
      java.lang.Object ref = label_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        label_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONFIDENCE_FIELD_NUMBER = 2;
    private float confidence_ = 0F;
    /**
     * <code>float confidence = 2;</code>
     * @return The confidence.
     */
    @java.lang.Override
    public float getConfidence() {
      return confidence_;
    }

    public static final int PREPROCESS_DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString preprocessData_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes preprocess_data = 3;</code>
     * @return The preprocessData.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPreprocessData() {
      return preprocessData_;
    }

    public static final int ATTENTION_DATA_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString attentionData_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes attention_data = 4;</code>
     * @return The attentionData.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getAttentionData() {
      return attentionData_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(label_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, label_);
      }
      if (java.lang.Float.floatToRawIntBits(confidence_) != 0) {
        output.writeFloat(2, confidence_);
      }
      if (!preprocessData_.isEmpty()) {
        output.writeBytes(3, preprocessData_);
      }
      if (!attentionData_.isEmpty()) {
        output.writeBytes(4, attentionData_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(label_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, label_);
      }
      if (java.lang.Float.floatToRawIntBits(confidence_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, confidence_);
      }
      if (!preprocessData_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, preprocessData_);
      }
      if (!attentionData_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, attentionData_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.example.modelbackend.ImageClassifierOuterClass.ImageResponse)) {
        return super.equals(obj);
      }
      org.example.modelbackend.ImageClassifierOuterClass.ImageResponse other = (org.example.modelbackend.ImageClassifierOuterClass.ImageResponse) obj;

      if (!getLabel()
          .equals(other.getLabel())) return false;
      if (java.lang.Float.floatToIntBits(getConfidence())
          != java.lang.Float.floatToIntBits(
              other.getConfidence())) return false;
      if (!getPreprocessData()
          .equals(other.getPreprocessData())) return false;
      if (!getAttentionData()
          .equals(other.getAttentionData())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LABEL_FIELD_NUMBER;
      hash = (53 * hash) + getLabel().hashCode();
      hash = (37 * hash) + CONFIDENCE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getConfidence());
      hash = (37 * hash) + PREPROCESS_DATA_FIELD_NUMBER;
      hash = (53 * hash) + getPreprocessData().hashCode();
      hash = (37 * hash) + ATTENTION_DATA_FIELD_NUMBER;
      hash = (53 * hash) + getAttentionData().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.example.modelbackend.ImageClassifierOuterClass.ImageResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.modelbackend.ImageClassifierOuterClass.ImageResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.modelbackend.ImageClassifierOuterClass.ImageResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.modelbackend.ImageClassifierOuterClass.ImageResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.modelbackend.ImageClassifierOuterClass.ImageResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.modelbackend.ImageClassifierOuterClass.ImageResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.modelbackend.ImageClassifierOuterClass.ImageResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.example.modelbackend.ImageClassifierOuterClass.ImageResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.example.modelbackend.ImageClassifierOuterClass.ImageResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.example.modelbackend.ImageClassifierOuterClass.ImageResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.modelbackend.ImageClassifierOuterClass.ImageResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.example.modelbackend.ImageClassifierOuterClass.ImageResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.example.modelbackend.ImageClassifierOuterClass.ImageResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.example.modelbackend.ImageResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.example.modelbackend.ImageResponse)
        org.example.modelbackend.ImageClassifierOuterClass.ImageResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.example.modelbackend.ImageClassifierOuterClass.internal_static_org_example_modelbackend_ImageResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.example.modelbackend.ImageClassifierOuterClass.internal_static_org_example_modelbackend_ImageResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.example.modelbackend.ImageClassifierOuterClass.ImageResponse.class, org.example.modelbackend.ImageClassifierOuterClass.ImageResponse.Builder.class);
      }

      // Construct using org.example.modelbackend.ImageClassifierOuterClass.ImageResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        label_ = "";
        confidence_ = 0F;
        preprocessData_ = com.google.protobuf.ByteString.EMPTY;
        attentionData_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.example.modelbackend.ImageClassifierOuterClass.internal_static_org_example_modelbackend_ImageResponse_descriptor;
      }

      @java.lang.Override
      public org.example.modelbackend.ImageClassifierOuterClass.ImageResponse getDefaultInstanceForType() {
        return org.example.modelbackend.ImageClassifierOuterClass.ImageResponse.getDefaultInstance();
      }

      @java.lang.Override
      public org.example.modelbackend.ImageClassifierOuterClass.ImageResponse build() {
        org.example.modelbackend.ImageClassifierOuterClass.ImageResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.example.modelbackend.ImageClassifierOuterClass.ImageResponse buildPartial() {
        org.example.modelbackend.ImageClassifierOuterClass.ImageResponse result = new org.example.modelbackend.ImageClassifierOuterClass.ImageResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.example.modelbackend.ImageClassifierOuterClass.ImageResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.label_ = label_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.confidence_ = confidence_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.preprocessData_ = preprocessData_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.attentionData_ = attentionData_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.example.modelbackend.ImageClassifierOuterClass.ImageResponse) {
          return mergeFrom((org.example.modelbackend.ImageClassifierOuterClass.ImageResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.example.modelbackend.ImageClassifierOuterClass.ImageResponse other) {
        if (other == org.example.modelbackend.ImageClassifierOuterClass.ImageResponse.getDefaultInstance()) return this;
        if (!other.getLabel().isEmpty()) {
          label_ = other.label_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getConfidence() != 0F) {
          setConfidence(other.getConfidence());
        }
        if (other.getPreprocessData() != com.google.protobuf.ByteString.EMPTY) {
          setPreprocessData(other.getPreprocessData());
        }
        if (other.getAttentionData() != com.google.protobuf.ByteString.EMPTY) {
          setAttentionData(other.getAttentionData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                label_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 21: {
                confidence_ = input.readFloat();
                bitField0_ |= 0x00000002;
                break;
              } // case 21
              case 26: {
                preprocessData_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                attentionData_ = input.readBytes();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object label_ = "";
      /**
       * <code>string label = 1;</code>
       * @return The label.
       */
      public java.lang.String getLabel() {
        java.lang.Object ref = label_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          label_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string label = 1;</code>
       * @return The bytes for label.
       */
      public com.google.protobuf.ByteString
          getLabelBytes() {
        java.lang.Object ref = label_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          label_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string label = 1;</code>
       * @param value The label to set.
       * @return This builder for chaining.
       */
      public Builder setLabel(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        label_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string label = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLabel() {
        label_ = getDefaultInstance().getLabel();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string label = 1;</code>
       * @param value The bytes for label to set.
       * @return This builder for chaining.
       */
      public Builder setLabelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        label_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private float confidence_ ;
      /**
       * <code>float confidence = 2;</code>
       * @return The confidence.
       */
      @java.lang.Override
      public float getConfidence() {
        return confidence_;
      }
      /**
       * <code>float confidence = 2;</code>
       * @param value The confidence to set.
       * @return This builder for chaining.
       */
      public Builder setConfidence(float value) {

        confidence_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>float confidence = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearConfidence() {
        bitField0_ = (bitField0_ & ~0x00000002);
        confidence_ = 0F;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString preprocessData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes preprocess_data = 3;</code>
       * @return The preprocessData.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getPreprocessData() {
        return preprocessData_;
      }
      /**
       * <code>bytes preprocess_data = 3;</code>
       * @param value The preprocessData to set.
       * @return This builder for chaining.
       */
      public Builder setPreprocessData(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        preprocessData_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>bytes preprocess_data = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPreprocessData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        preprocessData_ = getDefaultInstance().getPreprocessData();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString attentionData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes attention_data = 4;</code>
       * @return The attentionData.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getAttentionData() {
        return attentionData_;
      }
      /**
       * <code>bytes attention_data = 4;</code>
       * @param value The attentionData to set.
       * @return This builder for chaining.
       */
      public Builder setAttentionData(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        attentionData_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>bytes attention_data = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAttentionData() {
        bitField0_ = (bitField0_ & ~0x00000008);
        attentionData_ = getDefaultInstance().getAttentionData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.example.modelbackend.ImageResponse)
    }

    // @@protoc_insertion_point(class_scope:org.example.modelbackend.ImageResponse)
    private static final org.example.modelbackend.ImageClassifierOuterClass.ImageResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.example.modelbackend.ImageClassifierOuterClass.ImageResponse();
    }

    public static org.example.modelbackend.ImageClassifierOuterClass.ImageResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ImageResponse>
        PARSER = new com.google.protobuf.AbstractParser<ImageResponse>() {
      @java.lang.Override
      public ImageResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ImageResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ImageResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.example.modelbackend.ImageClassifierOuterClass.ImageResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_modelbackend_ImageRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_example_modelbackend_ImageRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_modelbackend_ImageResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_example_modelbackend_ImageResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026image_classifier.proto\022\030org.example.mo" +
      "delbackend\"\"\n\014ImageRequest\022\022\n\nimage_data" +
      "\030\001 \001(\014\"c\n\rImageResponse\022\r\n\005label\030\001 \001(\t\022\022" +
      "\n\nconfidence\030\002 \001(\002\022\027\n\017preprocess_data\030\003 " +
      "\001(\014\022\026\n\016attention_data\030\004 \001(\0142s\n\017ImageClas" +
      "sifier\022`\n\rClassifyImage\022&.org.example.mo" +
      "delbackend.ImageRequest\032\'.org.example.mo" +
      "delbackend.ImageResponseb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_example_modelbackend_ImageRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_example_modelbackend_ImageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_example_modelbackend_ImageRequest_descriptor,
        new java.lang.String[] { "ImageData", });
    internal_static_org_example_modelbackend_ImageResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_example_modelbackend_ImageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_example_modelbackend_ImageResponse_descriptor,
        new java.lang.String[] { "Label", "Confidence", "PreprocessData", "AttentionData", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
